version: 1.0.{build}
image: Visual Studio 2017
shallow_clone: true
pull_requests:
  do_not_increment_build_number: true
nuget:
  account_feed: true
test: off
build_script:
- ps: >-
    .\build.ps1
deploy_script:
- ps: >-
    .\build.ps1
artifacts:
  - path: artifacts\*.*